version: '3'

services:
  node-app:
    build: .
    container_name: 'lpsolve-node'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    networks:
      - blendcafe-network

networks:
  blendcafe-network:
    external: true
